### ISSUE TITLE
Specs keeps loading forever - 'TypeError: cannot read properties of undefined'

### ISSUE THREAD

**Issue by MahmoudTarek97** [vega/editor#1342]
The specs keeps loading forever:
![vega-editor-loading-specs-forever](https://github.com/vega/editor/assets/22938436/a1e02afe-c810-4ab6-aaf0-d5e45d7298be)

Clicking on Config tab leads to a blank page:
![clicking-on-config-tab-blank-page](https://github.com/vega/editor/assets/22938436/6231224b-efae-4f53-bc3d-37a5204dc886)

Error in Chrome 114.0.5735.111:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'focus')
    at Pyt.componentDidUpdate (index-de9aff5f.js:685:53094)
    at pCe (index-de9aff5f.js:39:1761)
    at bCe (index-de9aff5f.js:41:5093)
    at e.unstable_runWithPriority (index-de9aff5f.js:26:3881)
    at av (index-de9aff5f.js:37:38734)
    at fy (index-de9aff5f.js:41:1829)
    at IB (index-de9aff5f.js:39:11079)
    at index-de9aff5f.js:37:38960
    at e.unstable_runWithPriority (index-de9aff5f.js:26:3881)
    at av (index-de9aff5f.js:37:38734)
```

**Comment by domoritz** [comment]
If it's specific to a spec, this is not an issue with the editor I think. I'll close this for now as there I'll need reproduction instructions.
